// Generated by CoffeeScript 1.6.2
var use_space;

use_space = function(line) {
  return line.replace(/\t/g, "  ");
};

exports.indent = function(code) {
  var gather_indent, indent, lines;

  code = code.trim();
  indent = 80;
  gather_indent = function(line) {
    var after, before, diff;

    before = line.length;
    after = line.trimLeft().length;
    diff = before - after;
    if ((0 < diff && diff < indent)) {
      return indent = diff;
    }
  };
  lines = code.split("\n").map(String.prototype.trimRight.call).map(use_space).map(gather_indent);
  return indent;
};
