// Generated by CoffeeScript 1.6.2
var EventEmitter, all, delay, paper, paste, q, rain;

q = function(query) {
  return document.querySelector(query);
};

all = function(query) {
  return document.querySelectorAll(query);
};

EventEmitter = require("eventemitter").EventEmitter;

delay = function(t, f) {
  return setTimeout(f, t);
};

exports.rain = rain = new EventEmitter();

paste = q("#paste");

paper = q("#paper");

paper.onclick = function(event) {
  var elem, next, style;

  elem = event.target;
  if (elem.className === "line") {
    next = elem.nextElementSibling;
    style = next.style;
    if (style.opacity === "0") {
      elem.style.background = "none";
      return style.opacity = "1";
    } else if (next.childElementCount > 0) {
      elem.style.background = "hsl(240,80%,93%)";
      return style.opacity = "0";
    }
  }
};

q("#fold").onclick = function() {
  return Array.prototype.map.call(all(".block"), function(elem) {
    elem.style.opacity = "1";
    return elem.previousElementSibling.click();
  });
};

q("#expand").onclick = function() {
  return Array.prototype.map.call(all(".block"), function(elem) {
    elem.style.opacity = "0";
    return elem.previousElementSibling.click();
  });
};

paste.addEventListener("paste", function() {
  return delay(0, function() {
    return rain.emit("paste", paste.value);
  });
});

rain.on("render", function(html) {
  paper.innerHTML = html;
  return Array.prototype.map.call(all(".block"), function(elem) {
    return elem.style.opacity = "1";
  });
});
