// Generated by CoffeeScript 1.6.2
var EventEmitter, delay, elem, find, paper, rain;

find = function(query) {
  return document.querySelector(query);
};

EventEmitter = require("eventemitter").EventEmitter;

delay = function(t, f) {
  return setTimeout(f, t);
};

exports.rain = rain = new EventEmitter();

elem = find("#paste");

paper = find("#paper");

paper.onclick = function(event) {
  var next, style;

  elem = event.target;
  if (elem.className = "line") {
    next = elem.nextElementSibling;
    style = next.style;
    if (style.display === "none") {
      elem.style.background = "hsla(240,80%,90%,0)";
      return style.display = "block";
    } else if (next.childElementCount > 0) {
      elem.style.background = "hsl(240,80%,90%)";
      return style.display = "none";
    }
  }
};

elem.addEventListener("paste", function() {
  return delay(0, function() {
    return rain.emit("paste", elem.value);
  });
});

rain.on("render", function(html) {
  return paper.innerHTML = html;
});
