// Generated by CoffeeScript 1.6.2
var detect, get_indent, make_html, make_list, make_tree;

detect = require("./detect");

get_indent = function(line) {
  var match;

  match = line.match(/^(\s*)/);
  return match[0].length;
};

make_list = function(code) {
  return code.split("\n").map(function(line) {
    return line.trimRight();
  }).filter(function(line) {
    return line.length > 0;
  });
};

make_tree = function(lines) {
  var last, tree;

  tree = {};
  last = void 0;
  lines.forEach(function(line) {
    var indent, n;

    n = get_indent(line);
    indent = void 0;
    if (n === 0) {
      if (Array.isArray(tree[last])) {
        tree[last] = make_tree(tree[last]);
      }
      last = line;
      tree[last] = [];
      return indent = void 0;
    } else {
      if (indent == null) {
        indent = n;
      }
      return tree[last].push(line.slice(2));
    }
  });
  if (Array.isArray(tree[last])) {
    tree[last] = make_tree(tree[last]);
  }
  return tree;
};

make_html = function(tree) {
  var add, html, key, value;

  html = "";
  add = function(string) {
    return html += string;
  };
  for (key in tree) {
    value = tree[key];
    add("<div class='unit'>");
    add("<div class='line'>");
    add(key);
    add("</div>");
    add("<div class='block'>");
    add(make_html(value));
    add("</div>");
    add("</div>");
  }
  return html;
};

exports.convert = function(code) {
  return make_html(make_tree(make_list(code)));
};
